name: Petroleum Web build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.22.12]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
      - name: Install Dependencies
        run: npm install --package-lock-only --save
      - name: Install chalk
        run: npm install chalk
      - name: Build
        run: npm run build
      - name: Cat Log
        run: ls -t /home/runner/.npm/_logs/ | head -n 1 | xargs -I {} cat /home/runner/.npm/_logs/{}


